# /bin/sh
# ----------------Parameters---------------------- #
#$ -S /bin/sh
#$ -pe mthread 8
#$ -q sThC.q
#$ -l mres=32G,h_data=4G,h_vmem=4G
#$ -cwd
#$ -j y
#$ -N bwa
#
# ----------------Modules------------------------- #
#
# ----------------Your Commands------------------- #
#
echo + `date` job $JOB_NAME started in $QUEUE with jobID=$JOB_ID on $HOSTNAME
echo + NSLOTS = $NSLOTS
#
~/miniconda3/bin/bwa mem -t $NSLOTS Acer_yangbiense $1 | gzip -3 > $1.sam.gz
#
echo = `date` job $JOB_NAME done