# /bin/sh
# ----------------Parameters---------------------- #
#$ -S /bin/sh
#$ -q sThC.q
#$ -cwd
#$ -j y
#$ -N picard
#$ -o picard.log
#
# ----------------Modules------------------------- #
module load bioinformatics/picard-tools
#
# ----------------Your Commands------------------- #
#
echo + `date` job $JOB_NAME started in $QUEUE with jobID=$JOB_ID on $HOSTNAME
#
java -jar picard.jar NormalizeFasta I=VAHF01.fa O=normalized_VAHF01.fa
#
echo = `date` job $JOB_NAME done