# /bin/sh
# ----------------Parameters---------------------- #
#$ -S /bin/sh
#$ -pe mthread 8
#$ -q sThC.q
#$ -l mres=48G,h_data=6G,h_vmem=6G
#$ -cwd
#$ -j y
#
# ----------------Modules------------------------- #
module load bioinformatics/samtools
#
# ----------------Your Commands------------------- #
#
echo + `date` job $JOB_NAME started in $QUEUE with jobID=$JOB_ID on $HOSTNAME
echo + NSLOTS = $NSLOTS
#
samtools view -@ $NSLOTS -S -b $1 > $1.bam \

samtools sort -@ $NSLOTS $1.bam -o $1.sorted.bam
#
echo = `date` job $JOB_NAME done